FROM python:slim

ENV TERM xterm-256color
RUN apt-get update
RUN apt-get install -y git gcc python3-dev zlib1g-dev libjpeg-dev
RUN pip install --upgrade pip
RUN pip install virtualenv
RUN echo "alias ls='ls --color=auto'" >> ~/.bashrc
RUN echo "alias ll='ls --color=auto -l'" >> ~/.bashrc
RUN echo "alias l='ls --color=auto -lA'" >> ~/.bashrc
RUN echo "alias la='ls --color=auto -la'" >> ~/.bashrc
RUN echo "alias lr='ls  --color=auto -lart'" >> ~/.bashrc